### ISSUE TITLE
Add NUnit 2 icons

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/resources#4]
The nunit-vs-adapter uses the NUnit 2 logo, but only a 32x32 version. 

Is anyone able to add 90x90 and 256x256 versions of this v2 icon to this repo, so we can update the vsix and nuspec as the other projects? @CharliePoole?

**Comment by CharliePoole** [comment]
@rprouse What feature are you using to make the "4 of 16 tasks complete" message show up above?

**Comment by CharliePoole** [comment]
@ChrisMaddock I'll have to check what I have on my computer at home - nothing on this new laptop. I believe I have the original art saved.

**Comment by ChrisMaddock** [comment]
> What feature are you using to make the "4 of 16 tasks complete" message show up above?

That was me sorry, I took the liberty of editing the checklist into Rob's opening post, to save my scrolling. Doing that added the 4/16 tasks thing. 

> I'll have to check what I have on my computer at home - nothing on this new laptop.

Thanks!

**Comment by CharliePoole** [comment]
I see that you can add a "task list" but I didn't understand it was an actual github feature. Now that I have read the docs, I'm wondering when it's best to use them versus the ZenHub epics we have been using. Tentatively, I'm thinking separate release requires a separate issue (i.e. use Epics) whereas tasks have to do with items that have to be completed all together, in one repo, before the release can occur.

**Comment by CharliePoole** [comment]
The best image I have available is at http://nunit.org/img/logo.gif

I created the 32x32 icon out of that.

**Comment by ChrisMaddock** [comment]
Thanks for looking @CharliePoole 😄 If that's the original, then we can just leave the v2 adapter with the icon it has - hopefully it's soon to be merged into the single NUnit adapter anyway!

**Comment by CharliePoole** [comment]
Not that soon, I suspect.
